### ISSUE TITLE
[Feature Request] - Enhanced Logging

### ISSUE THREAD

**Issue by n1nj4888** [loganmarchione/docker-speedtest-influxdb#1]
Hi there,

Looks like a good start on the speedtest influxdb logging but I wondered whether I could request a couple of enhancements?

1) Add an extra environment variable called say "SPEEDTEST_HOST" which is written to each influx "speedtest" measurement as a "host" tag (i.e. "host" = <SPEEDTEST_HOST>)? This allows multiple servers to write to use the same docker image and write to the same influxdb but with different "host" tags so that these can be filtered by host. The user could then start the docker container on server1 with SPEEDTEST_HOST="server1" and also started on server2 with SPEEDTEST_HOST="server2" - Both servers would then write to the same DB/measurement but would be able to be filtered by the "host" tag.

2)  The speedtest CLI application outputs many more fields in the JSON output including details on the speedtest server, city, country, distance etc which would also be great to add to the influx measurement!

Thanks!

**Comment by loganmarchione** [comment]
@n1nj4888  - I am no longer maintaining this version of the container. I have a v2 container, [here](https://github.com/loganmarchione/docker-speedtest-influxdbv2), where I added these features. The v2 container uses the new Python library, which is **only** compatible with InfluxDB v1.8 and above.

The version you'll need is `loganmarchione/docker-speedtest-influxdbv2:0.0.10`. I didn't want to add too many measurements that people won't use, but I added `server_id`, `server_name`, `server_location`, `server_country`, and `server_host`. There was no distance field.

I'll add a note to the README that this container is no longer maintained.
